command:
  - "bash"
  - "start.sh"

env:
  - name: WILIOT_API_KEY
    description: "Wiliot Platform API key"
    value: ""
  - name: WILIOT_OWNER_ID
    description: "Wiliot Platform owner ID"
    value: ""
  - name: SMTP_HOST
    description: "SMTP server host"
    value: "email-smtp.us-east-1.amazonaws.com"
  - name: SMTP_PORT
    description: "SMTP server port"
    value: "587"
  - name: SMTP_USERNAME
    description: "SMTP username"
    value: ""
  - name: SMTP_PASSWORD
    description: "SMTP password"
    value: ""
  - name: SMTP_SENDER
    description: "Sender email address"
    value: "solutions@wiliot.com"
  - name: RESULTS_RECIPIENT
    description: "Email recipient for creation results"
    value: "fernando.carrero@wiliot.com"
